[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

  [[redirects]]
   from = "/shows/abbey-theatre/*"
   to = "/abbey-theatre/:splat"
   status = 302
